#!/bin/sh
# Applications
~/.config/polybar/launch.sh &
pgrep conky || ~/.config/conky/start-conky.sh &
pidof redshift || redshift &

pidof kitty || kitty &
pidof firefox || firefox &
pidof skypeforlinux || skypeforlinux &
pidof zathura || zathura &
pidof thunderbird || thunderbird &

#xautolock -detectsleep -time 5 -locker lock.sh -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &
#mailsync &
