#!/bin/bash

#### MONITORS ####

export HARDWARECLOCK=localtime
export _JAVA_AWT_WM_NONREPARTENTING=1

external_monitor_status=$(xrandr | grep HDMI1 | awk '{print $2}')
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

export BROWSER=firefox
export $(dbus-launch)

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

bspc monitor eDP1 -d I II III IV V
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal 

[[ $external_monitor_status = "connected" ]] && xrandr --output HDMI1 --mode 1280x800 --rotate inverted --right-of eDP1 && bspc monitor HDMI1 -d VI VII VIII XI X 
	


# Truncate a couple of common commands that are used herein.
_bc() {
	bspc config "$@"
}


#### BSPWM configuration ####
_bc window_gap 			  						8
_bc top_padding 									26
_bc top_monocle_padding 					0
_bc border_width 								  2
_bc bottom_padding                0
_bc left_padding                  0
_bc right_padding 								0
_bc single_monocle                false
_bc click_to_focus                false
_bc split_ratio                   0.50
_bc borderless_monocle            true
_bc gapless_monocle               true
_bc focus_by_distance             true
_bc paddingless_monocle  	  			true
_bc focus_follows_pointer         true
_bc ignore_ewmh_focus 		  			true
_bc history_aware_focus           true
_bc remove_disabled_monitors      true
_bc merge_overlapping_monitors    true
_bc pointer_follows_monitor 			true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
bspc config active_border_color "#474f54"
bspc config focused_border_color "#474f54"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

# Rules
bspc desktop -f I II III IV V VI VII VIII IX X

bspc rule -a kitty desktop='I'
bspc rule -a Firefox desktop='II'
bspc rule -a Skype desktop='III'
bspc rule -a Zathura desktop='IV' state='tiled'
bspc rule -a Thunderbird desktop='V'

# INIT-DAEMONS
xsetroot -cursor_name left_ptr &
sxhkd &
# xcompmgr -cCfF -t -2 -l -2 -r 2.8 -o 0.55 -D 5 &
#picom --experimental-backends &
picom &
dunst &

# Replace caps lock with Esc
# setxkbmap -option caps:escape
setxkbmap -option caps:backspace

# AUTOSTART
# set wallpaper using hsetroot
feh  --bg-fill $HOME/.wallpaper/wallpaper.jpg &
~/.config/bspwm/autostart &
